#!/usr/bin/env bash
# =============================================================================
# lazado — init.sh
# Setup wizard: ado-init
# =============================================================================

ado-init() {
  echo ""
  echo "lazado — Setup Wizard"
  echo "====================="
  echo ""

  # Check dependencies first
  if ! _lazado_check_deps; then
    _lazado_err "Please install missing dependencies before continuing."
    return 1
  fi

  # Check az login
  if ! az account show &>/dev/null 2>&1; then
    _lazado_err "Not logged in to Azure CLI. Run 'az login' first."
    return 1
  fi

  local user
  user=$(_lazado_me)
  echo "Logged in as: $user"
  echo ""

  # -- Organization --
  local detected_org="" detected_project=""

  # Try to auto-detect from current git remote
  local remote_url
  remote_url=$(git config --get remote.origin.url 2>/dev/null)
  if [[ -n "$remote_url" ]]; then
    if [[ "$remote_url" =~ ssh\.dev\.azure\.com.*v3/([^/]+)/([^/]+)/ ]]; then
      detected_org="${BASH_REMATCH[1]}"
      detected_project="${BASH_REMATCH[2]}"
    elif [[ "$remote_url" =~ dev\.azure\.com/([^/]+)/([^/]+)/ ]]; then
      detected_org="${BASH_REMATCH[1]}"
      detected_project="${BASH_REMATCH[2]}"
    elif [[ "$remote_url" =~ ([^/]+)\.visualstudio\.com/([^/]+)/ ]]; then
      detected_org="${BASH_REMATCH[1]}"
      detected_project="${BASH_REMATCH[2]}"
    fi
  fi

  local org_name
  if [[ -n "$detected_org" ]]; then
    read -rp "Organization name [$detected_org]: " org_name
    org_name="${org_name:-$detected_org}"
  else
    read -rp "Organization name (e.g., MyCompany): " org_name
    if [[ -z "$org_name" ]]; then
      _lazado_err "Organization name is required."
      return 1
    fi
  fi

  local org_url="https://dev.azure.com/$org_name"

  # -- Project --
  local project
  if [[ -n "$detected_project" ]]; then
    read -rp "Project name [$detected_project]: " project
    project="${project:-$detected_project}"
  else
    read -rp "Project name: " project
    if [[ -z "$project" ]]; then
      _lazado_err "Project name is required."
      return 1
    fi
  fi

  # -- Validate connection --
  echo ""
  _lazado_info "Validating connection to $org_url/$project..."
  if ! az devops project show --project "$project" --org "$org_url" --output none 2>/dev/null; then
    _lazado_warn "Could not validate project. Check the org/project name and your permissions."
    read -rp "Continue anyway? [y/N]: " cont
    [[ ! "$cont" =~ ^[Yy]$ ]] && return 1
  else
    echo "Connection verified."
  fi

  # -- Clone directory --
  local clone_dir
  read -rp "Clone directory [$HOME/dev]: " clone_dir
  clone_dir="${clone_dir:-$HOME/dev}"

  # -- Branch prefix --
  local branch_prefix
  read -rp "Branch prefix for new branches [feature]: " branch_prefix
  branch_prefix="${branch_prefix:-feature}"

  # -- Default target branch --
  local target_branch
  read -rp "Default PR target branch [main]: " target_branch
  target_branch="${target_branch:-main}"

  # -- Write config --
  local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/lazado"
  mkdir -p "$config_dir"

  cat > "$config_dir/config" <<EOF
# lazado configuration
# Generated by ado-init

org=$org_url
project=$project
clone_dir=$clone_dir
branch_prefix=$branch_prefix
default_target_branch=$target_branch
cache_ttl=86400
EOF

  echo ""
  echo "Config written to: $config_dir/config"

  # -- Reload config --
  _lazado_load_config

  # -- Cache states --
  echo ""
  _lazado_info "Fetching work item states..."
  ado-refresh-states

  # -- Project-level config --
  echo ""
  local git_root
  git_root=$(git rev-parse --show-toplevel 2>/dev/null)
  if [[ -n "$git_root" ]]; then
    read -rp "Create .adoconfig in $git_root for team sharing? [y/N]: " create_project
    if [[ "$create_project" =~ ^[Yy]$ ]]; then
      cat > "$git_root/.adoconfig" <<EOF
# lazado project config — share with your team
project=$project
default_target_branch=$target_branch
branch_prefix=$branch_prefix
EOF
      echo "Created $git_root/.adoconfig"
    fi
  fi

  echo ""
  echo "Setup complete. Type 'ado' to get started."
}
